backend/app/core/deps.py
backend/app/domains/auth/routes.py
backend/app/domains/auth/schemas.py
backend/app/domains/auth/services.py

login, logout, refresh token api
refresh token 을 HttpOnly Cookie로 관리, refresh API 수정
Closes #20
-

#20 feat: Add HttpOnly Cookie managed refresh token

---

frontend/src/components/molecule/BillingListItem/BillingListItem.module.css
frontend/src/components/molecule/BillingListItem/BillingListItem.tsx
frontend/src/components/molecule/BillingListItem/index.ts
frontend/src/components/organism/Subscription/Subscription.module.css
frontend/src/components/organism/Subscription/Subscription.tsx
frontend/src/utils/getBillingTag.ts

- 마이페이지 > 구독 관리 탭 > 결제 정보 표시 UI 구현
Closes #150

#150 feat: mypage > subscription tab 결제 정보 표시 UI 구현

---

frontend/src/App.tsx
frontend/src/assets/icons/checked.svg
frontend/src/components/atom/Checkbox/Checkbox.module.css
frontend/src/components/atom/Checkbox/Checkbox.tsx
frontend/src/components/atom/Checkbox/index.ts
frontend/src/components/organism/Account/Account.tsx
frontend/src/pages/DeleteAccount/DeleteAccount.module.css
frontend/src/pages/DeleteAccount/DeleteAccount.tsx
frontend/src/stories/Checkbox.module.css
frontend/src/stories/Checkbox.stories.ts
frontend/src/stories/Checkbox.tsx

- 마이페이지 > 계정 관리 탭 > 회원 탈퇴 UI 구현
Closes #147, #148

#147 feat: mypage > 회원 탈퇴 UI 구현

---

backend/app/domains/auth/routes.py
backend/app/domains/auth/schemas.py

회원가입 화면에서 사용할 이메일 중복확인 API
Closes #108 
https://www.notion.so/ec14e67c5dc2411a919dc7c2143b6d23
- 
-

#108 feat: 이메일 중복확인 API 추가

---

backend/app/domains/auth/routes.py
backend/app/domains/user/routes.py

핸드폰 인증번호 확인 API 추가
핸드폰 번호를 cookie에 포함하여 이후 요청에 핸드폰 번호를 사용하는 경우(예:회원가입 정보) 검증할 수 있도록 한다.
Closes #110 
- 
-

#110 feat: 핸드폰 인증 번호 확인 API 추가

---

db/init.sql

이메일/비밀번호 로그인 테스트 위한 계정 추가
Closes #20
- [X] 기타 (설명해주세요): 테스트 계정 데이터 초기화 insert 구문 추가
- 
-

#20 chore: 테스트 사용자 계정 init.sql 추가

---

backend/app/domains/auth/routes.py
db/init.sql

회원 가입 완료 후 응답 처리 및 테스트 계정 추가
Closes #107
- 
-

#107 fix: 회원 가입 API 응답 설정시 오류 수정, chore : 베타 테스트 계정 추가

---

frontend/src/api/index.ts

로그인 API 요청 링크 수정
Closes hotfix
- 
-

fix: 로그인 관련 api path 수정

---

backend/app/domains/auth/routes.py
backend/app/domains/user/services.py

핸드폰 번호, 생년월일 기준 이메일 찾기 추가
Closes #112 
- 
-

feat: 핸드폰 번호, 생년월일 기준 이메일 찾기 기능 추가

---

frontend/src/App.tsx
frontend/src/api/index.ts
frontend/src/constants/oauth.ts
frontend/src/pages/Login/Login.tsx
frontend/src/pages/OAuthCallback/OAuthCallback.tsx
frontend/src/utils/tokenService.ts

feat: SNS 로그인 구현

---

backend/app/domains/auth/routes.py
frontend/src/App.tsx
frontend/src/pages/Chat/[chat_id]/ChatDetail.tsx
frontend/src/pages/Signup/Signup.tsx

SNS 인증 후 회원 가입시 핸드폰 번호 인증 제외
채팅 상세페이지 제목, 추천 질문 변경
tanstack-devtool(야자수 친구) 주석처리
생년월일 YYYY-MM-DD 형식으로 onChange 식으로 자동 변환
Closes #
- [X] 버그 수정
- 
-

SNS 로그인 로직 수정

---

backend/app/domains/auth/routes.py
backend/app/domains/user/models.py
db/init.sql

SNS 로그인 후 가입 시 핸드폰 번호 중복 확인 제거 
Closes #
- [X] 새로운 기능
- 
-

Hotfix skip phone no check

---

backend/app/domains/auth/routes.py

#187 feat: 로그아웃 API 개선, 모든 쿠키 제거, 회원 가입후 관련 쿠키 제거

---

backend/app/domains/auth/routes.py

비밀번호 변경을 위해 핸드폰 인증 API를 수정함
회원 가입시 핸드폰 중복확인 절차가 있었으나 생략할 수 있도록 사용자 요청 본문에 변수 추가함
Closes #191 
- 
-

#191 feat: 로그인 전 비밀번호 재설정 위한 API 추가 및 핸드폰 인증 API 수정

---

backend/app/domains/payment/models.py
backend/app/domains/payment/routes.py
backend/app/domains/payment/schemas.py
backend/app/domains/payment/services.py
backend/app/domains/subscription/schemas.py
backend/tests/index_payment.html

쿠폰 유효성 검증 API 파라미터 수정
결제 관련 코드 정리
Closes #
- 
-

fix: 코드 정리, 쿠폰 유효성 검증 API 파라미터 수정

---

backend/app/domains/payment/routes.py
backend/app/domains/payment/services.py
backend/tests/index_payment.html

카카오 결제 api : 결제 서비스 인스턴스 설정
Closes # 72
- 
-

fix: /pay API 버그 수정

---

backend/app/domains/payment/models.py
backend/app/domains/payment/routes.py
backend/app/domains/payment/schemas.py
backend/app/domains/payment/services.py
backend/app/domains/subscription/services.py
db/init.sql

결제 캐시 : 단일 유저(테스트) 전용 캐시 정보 저장 -> DB에 결제 캐시 테이블을 활용해서 저장
자동 정기 구독, 단일 정기 구독, 결제 수단 변경  기능 수정 및 테스트 
결제 실패 리다이렉트 기능 버그 수정
Closes #71
- 
-

feat: 결제 캐시 기능 구현, 결제 실패 기능 수정

---

backend/app/domains/user/routes.py
backend/app/domains/user/schemas.py

마이페이지 비밀번호 확인 API 오류 수정
Closes #200 
- [X] 버그 수정
- 
-

fix: 마이페이지 비밀번호 확인 POST /users/me/password API 오류 수정

---

backend/app/domains/payment/routes.py
backend/app/domains/payment/services.py

배포 서버 결제 오류 수정
Closes #71
- 
-

fix: 배포 서버 결제 오류 수정

---

backend/app/domains/user/routes.py

#205 feat: 현재 사용자 정보 불러오기 API 추가

---

backend/app/domains/payment/routes.py
backend/app/domains/payment/schemas.py
backend/app/domains/payment/services.py

기존 간단하게 구현(첨부 기능 x)만 했던 결제 취소 문의 API를 업데이트
Closes #71
- 
-

fix: 결제 취소 문의 API 수정

---

backend/app/domains/subscription/models.py
backend/app/domains/user/routes.py
backend/app/domains/user/schemas.py
backend/app/domains/user/services.py

#208 fix: 사용자 정보 현재 구독 플랜 조회시 오류 수정

---

backend/app/domains/user/routes.py

구독 정보 없는 사용자 계정에서 API호출시 오류
NoneType 처리함
Closes #208 
- 
-

#208 GET /users/me API 호출 시 오류

---

backend/app/domains/payment/portone_services.py
backend/app/domains/payment/routes.py
backend/app/domains/payment/schemas.py

PortOne 구독 결제 방식 변경 로직 업데이트 - 결제 웹훅 '결제 방식 변경 처리' 요청 구분 로직 추가
모바일 결제 다이렉트 오류 수정
Closes #71
- 
-

feat: PortOne 구독 결제 방식 변경 로직 업데이트

---

backend/app/domains/payment/portone_services.py
backend/app/domains/payment/routes.py

포트원 쿠폰 사용 결제 검증 api 오류 해결
Closes #72
- 
-

fix: PortOne 쿠폰 결제 오류 해결

---

backend/app/domains/payment/routes.py
backend/app/domains/payment/services.py

fix: 결제 취소 문의 오류 수정

---

backend/app/domains/payment/services.py

fix: admin 결제 조회 서비스 코드 수정

---

backend/app/domains/payment/portone_services.py

feat: 구독 결제 기간 파라미터 설정
